### ISSUE TITLE
CRUD dos Clientes

### ISSUE THREAD

**Issue by WesleyVitor** [WesleyVitor/ProjetoES#3]
- [x] Cadastrar cliente
- [x] Exclusão lógica do cliente
- [x] Visualização dos clientes cadastrados

No formulário de cadastro de cliente terá os seguintes campos:
- Nome do cliente
- Cpf do cliente
- Email
- Celular

**Comment by karlianev** [comment]
É necessário colocar a descrição em cada tarefa para que toda equipe entenda o que deve ser desenvolvido. Essa tarefa por exemplo, o que é ler e criar cliente? é o crud de cliente? Entenda que não é apenas você quem vai utilizar/desenvolver a tarefa, então a descrição deve ser clara e objetiva para que qualquer pessoa da equipe leia e consiga executar a tarefa.
Esse comentário é válido para as demais tarefas.
